### ISSUE TITLE
DIY-1 audio file

### ISSUE THREAD

**Issue by lw2dtz** [daniestevez/satellite-recordings#6]
Hola Daniel,

Te envio una grabacion del DIY-1 en FSK a 500 Bd para tu coleccion de audios.

73 de Gustavo,LW2DTZ

https://user-images.githubusercontent.com/6095237/118571732-19547280-b755-11eb-97c9-5b966a6d98c7.mp4

**Comment by daniestevez** [comment]
Hola Gustavo, el formato para las grabaciones de este repositorio es WAV 48ksps mono con una duración de pocos segundos y uno o varios paquetes de datos. El nombre de la grabación debería reflejar el nombre del satélite. ¿Puedes por favor enviar un pull request con ese formato? En el caso de haber obtenido la grabación como un extracto de una observación de SatNOGS, conviene indicar el número de observación en el mensaje de commit.
